export { pool, query, checkConnection } from './client.js'
export { buildHealthStatus, checkDatabase, checkRedis, checkOutbox } from './health.js'
export type { HealthStatus, CheckResult } from './health.js'
export { registerAttachmentRoutes, getAttachments, createAttachment, removeAttachment } from './attachments.js'
export type { EntityType, AttachmentRouteOptions } from './attachments.js'
export type { PoolClient, QueryResult } from './client.js'
export { withRLS, setRLSContext } from './rls.js'
export { withTransaction, withSystemTransaction, withIntercoTransaction } from './transaction.js'
export type { TransactionContext } from './transaction.js'
