const pg = require('c:\\Users\\PC\\OneDrive - Farage Printing Industries\\Desktop\\FNC ERP\\node_modules\\.pnpm\\pg@8.21.0\\node_modules\\pg')
const client = new pg.Client({ connectionString: process.env.DATABASE_URL })
client.connect().then(async () => {
  const pos = await client.query("SELECT po_number, status, currency_code, total_amount, notes FROM purchase_orders WHERE project_id = '30000000-0000-0000-0000-000000000001' ORDER BY po_number")
  console.log('\nPOs on project:')
  pos.rows.forEach(r => console.log(' ', r.po_number, '|', r.status, '|', r.currency_code, r.total_amount, '|', r.notes.substring(0,40)))
  const st = await client.query("SELECT name, sequence, status, completion_pct FROM project_stages WHERE project_id = '30000000-0000-0000-0000-000000000001' ORDER BY sequence")
  console.log('\nStages:')
  st.rows.forEach(r => console.log(' ', r.sequence, r.name, '|', r.status, r.completion_pct + '%'))
  const mem = await client.query("SELECT pm.role, e.first_name, e.last_name FROM project_members pm JOIN employees e ON e.id = pm.employee_id WHERE pm.project_id = '30000000-0000-0000-0000-000000000001'")
  console.log('\nMembers:')
  mem.rows.forEach(r => console.log(' ', r.role, ':', r.first_name, r.last_name))
  await client.end()
}).catch(function(e){ console.error('ERR:', e.message); process.exit(1) })
