export { sendEmail } from './sender.js'
export type { EmailMessage } from './sender.js'
export type { SmtpConfig } from './client.js'
export { renderPayslipEmail } from './templates/payslip.js'
export { renderInvoiceEmail } from './templates/invoice.js'
export { renderPOConfirmationEmail } from './templates/po-confirmation.js'
export { renderPasswordResetEmail } from './templates/password-reset.js'
export { renderPasswordChangedEmail } from './templates/password-changed.js'
export { renderMFASetupEmail } from './templates/mfa-setup.js'
export { renderNewDeviceLoginEmail } from './templates/new-device-login.js'
export { renderClientDocumentEmail } from './templates/client-document.js'
export { renderEngineeringRevisionEmail } from './templates/engineering-revision.js'
