import { useState, useEffect } from 'react'
import { useParams, useNavigate, useSearchParams } from 'react-router-dom'
import { useTheme } from '../../../theme/ThemeContext'
import { useToastStore } from '../../../store/toastStore'
import { api } from '../../../lib/axios'
import { apiErrMsg, apiErrCode } from '../../../lib/apiError'
import { PageHeader } from '../../../components/ui/PageHeader'
import { Card } from '../../../components/ui/Card'
import { Button } from '../../../components/ui/Button'
import { SearchableSelect } from '../../../components/ui/SearchableSelect'
import { Select } from '../../../components/ui/Select'
import { LineItemEditor, type LineItemField } from '../../../components/ui/LineItemEditor'

interface Vendor {
  id: string
  name: string
  currency_code: string
  withholding_tax_rate?: string
}
interface PO {
  id: string
  po_number: string
  vendor_id: string
  currency_code: string
}
interface POLine {
  id: string
  description: string
  qty_ordered: string
  unit_price: string
  account_id?: string
}
interface FullPO {
  id: string
  po_number: string
  vendor_id: string
  currency_code: string
  analytic_account_id?: string
  lines: POLine[]
}
interface CostCenter {
  id: string
  code: string
  name: string
}
interface AnalyticAccount {
  id: string
  code: string
  name: string
}
interface ChartAccount {
  id: string
  code: string
  name: string
}

interface LineForm {
  _key: string
  po_line_id: string
  description: string
  qty: string
  unit_price: string
  account_id: string
}

interface FormState {
  vendor_id: string
  po_id: string
  invoice_number: string
  invoice_date: string
  due_date: string
  currency_code: string
  tax_amount: string
  notes: string
  analytic_account_id: string
  cost_center_id: string
  wht_applies: boolean
  wht_rate: string
}

const CURRENCIES = [
  { value: 'IQD', label: 'IQD — Iraqi Dinar' },
  { value: 'USD', label: 'USD — US Dollar' },
  { value: 'EUR', label: 'EUR — Euro' },
  { value: 'GBP', label: 'GBP — British Pound' },
  { value: 'AED', label: 'AED — UAE Dirham' },
  { value: 'SAR', label: 'SAR — Saudi Riyal' },
  { value: 'TRY', label: 'TRY — Turkish Lira' },
]

function autoInvNumber(poNumber?: string): string {
  if (poNumber) {
    // PO-178219... → INV-178219...
    return 'INV-' + poNumber.replace(/^PO-/i, '')
  }
  const d = new Date()
  const ymd = `${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}`
  return `INV-${ymd}`
}

function isAutoGenerated(val: string): boolean {
  return val.startsWith('INV-') || val === ''
}

function mkLine(): LineForm {
  return {
    _key: Math.random().toString(36).slice(2),
    po_line_id: '',
    description: '',
    qty: '1',
    unit_price: '0',
    account_id: '',
  }
}

function mkLineFromPO(pl: POLine): LineForm {
  return {
    _key: Math.random().toString(36).slice(2),
    po_line_id: pl.id,
    description: pl.description ?? '',
    qty: String(pl.qty_ordered ?? 1),
    unit_price: String(pl.unit_price ?? 0),
    account_id: pl.account_id ?? '',
  }
}

function inputStyle(theme: Record<string, string>) {
  return {
    width: '100%',
    padding: '7px 10px',
    borderRadius: '6px',
    border: `1px solid ${theme.border}`,
    background: theme.bgSurface,
    color: theme.textPrimary,
    fontSize: '12px',
    boxSizing: 'border-box' as const,
  }
}
function labelStyle(theme: Record<string, string>) {
  return {
    display: 'block' as const,
    fontSize: '11px',
    color: theme.textMuted,
    marginBottom: '4px',
  }
}

export default function VendorInvoiceForm() {
  const { id } = useParams<{ id: string }>()
  const isEdit = !!id
  const { theme } = useTheme()
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const addToast = useToastStore((s) => s.addToast)
  const prefilledPoId = searchParams.get('po_id') ?? ''

  const [vendors, setVendors] = useState<Vendor[]>([])
  const [pos, setPOs] = useState<PO[]>([])
  const [poLines, setPOLines] = useState<POLine[]>([])
  const [costCenters, setCostCenters] = useState<CostCenter[]>([])
  const [analyticAccounts, setAnalyticAccounts] = useState<AnalyticAccount[]>([])
  const [chartAccounts, setChartAccounts] = useState<ChartAccount[]>([])
  const [loading, setLoading] = useState(isEdit)
  const [saving, setSaving] = useState(false)

  const [form, setForm] = useState<FormState>({
    vendor_id: '',
    po_id: prefilledPoId,
    invoice_number: isEdit ? '' : autoInvNumber(),
    invoice_date: new Date().toISOString().slice(0, 10),
    due_date: '',
    currency_code: 'IQD',
    tax_amount: '0',
    notes: '',
    analytic_account_id: '',
    cost_center_id: '',
    wht_applies: false,
    wht_rate: '0',
  })
  const [lines, setLines] = useState<LineForm[]>([mkLine()])

  useEffect(() => {
    void Promise.all([
      api.get<Vendor[]>('/procurement/vendors').then((r) => {
        setVendors(Array.isArray(r.data) ? r.data : [])
      }),
      api.get<{ items?: PO[]; data?: PO[] } | PO[]>('/procurement/purchase-orders').then((r) => {
        const d = r.data as unknown
        if (Array.isArray(d)) setPOs(d as PO[])
        else setPOs((d as { items?: PO[] }).items ?? [])
      }),
      api.get<CostCenter[]>('/finance/cost-centers').then((r) => {
        setCostCenters(Array.isArray(r.data) ? r.data : [])
      }),
      api.get<AnalyticAccount[]>('/finance/analytic-accounts').then((r) => {
        setAnalyticAccounts(Array.isArray(r.data) ? r.data : [])
      }),
      api.get<ChartAccount[]>('/finance/accounts').then((r) => {
        setChartAccounts(Array.isArray(r.data) ? r.data : [])
      }),
    ])
  }, [])

  useEffect(() => {
    if (!isEdit) return
    setLoading(true)
    api
      .get<{
        id: string
        vendor_id: string
        po_id?: string
        invoice_number: string
        invoice_date: string
        due_date: string
        currency_code: string
        tax_amount: string
        notes?: string
        analytic_account_id?: string
        cost_center_id?: string
        wht_applies?: boolean
        wht_rate?: string
        lines: LineForm[]
      }>(`/finance/vendor-invoices/${id}`)
      .then((r) => {
        const inv = r.data
        const invWhtRate = parseFloat(inv.wht_rate ?? '0')
        setForm({
          vendor_id: inv.vendor_id,
          po_id: inv.po_id ?? '',
          invoice_number: inv.invoice_number,
          invoice_date: inv.invoice_date?.slice(0, 10) ?? '',
          due_date: inv.due_date?.slice(0, 10) ?? '',
          currency_code: inv.currency_code ?? 'IQD',
          tax_amount: inv.tax_amount ?? '0',
          notes: inv.notes ?? '',
          analytic_account_id: inv.analytic_account_id ?? '',
          cost_center_id: inv.cost_center_id ?? '',
          wht_applies: inv.wht_applies ?? false,
          wht_rate: String(invWhtRate * 100),
        })
        if (inv.lines?.length) {
          setLines(
            inv.lines.map((l: LineForm) => ({
              _key: l._key ?? Math.random().toString(36).slice(2),
              po_line_id: l.po_line_id ?? '',
              description: l.description ?? '',
              qty: String(l.qty ?? 1),
              unit_price: String(l.unit_price ?? 0),
              account_id: l.account_id ?? '',
            })),
          )
        }
      })
      .catch(() => {
        addToast({ type: 'error', message: 'Failed to load invoice' })
      })
      .finally(() => {
        setLoading(false)
      })
  }, [id, isEdit, addToast])

  useEffect(() => {
    if (!form.po_id) {
      setPOLines([])
      if (!isEdit) {
        setLines([mkLine()])
        setForm((f) => ({
          ...f,
          invoice_number: isAutoGenerated(f.invoice_number) ? autoInvNumber() : f.invoice_number,
        }))
      }
      return
    }
    api
      .get<FullPO>(`/procurement/purchase-orders/${form.po_id}`)
      .then(async (r) => {
        const po = r.data
        const poLineList = po.lines ?? []
        setPOLines(poLineList)
        if (!isEdit && poLineList.length > 0) setLines(poLineList.map(mkLineFromPO))
        const autoInvNum = autoInvNumber(po.po_number)
        const vendorId = po.vendor_id || ''
        setForm((f) => ({
          ...f,
          vendor_id: f.vendor_id || vendorId,
          currency_code: po.currency_code || f.currency_code,
          analytic_account_id: f.analytic_account_id || po.analytic_account_id || '',
          invoice_number: isEdit
            ? f.invoice_number
            : isAutoGenerated(f.invoice_number)
              ? autoInvNum
              : f.invoice_number,
        }))
        // On new invoice: check immediately if one already exists for this vendor+number
        if (!isEdit && vendorId) {
          try {
            const dup = await api.get<{ items: { id: string }[] }>('/finance/vendor-invoices', {
              params: {
                vendor_id: vendorId,
                invoice_number: autoInvNum,
                cross_company: 'true',
                limit: 1,
              },
            })
            const existing = dup.data?.items?.[0]
            if (existing) {
              addToast({
                type: 'warning',
                message: `Invoice ${autoInvNum} already exists for this vendor — opening it`,
              })
              navigate(`/finance/ap/${existing.id}`)
            }
          } catch {
            /* ignore, user can still save and get the cleaner error */
          }
        }
      })
      .catch(() => {})
  }, [form.po_id])

  useEffect(() => {
    if (form.vendor_id) {
      const vendor = vendors.find((v) => v.id === form.vendor_id)
      if (vendor) {
        const vendorRate = parseFloat(vendor.withholding_tax_rate ?? '0')
        setForm((prev) => ({
          ...prev,
          // Keep PO currency if a PO is linked; otherwise use vendor default
          currency_code: prev.po_id ? prev.currency_code : (vendor.currency_code ?? 'IQD'),
          wht_applies: vendorRate > 0,
          wht_rate: vendorRate > 0 ? String(vendorRate * 100) : '0',
        }))
      }
    }
  }, [form.vendor_id, vendors])

  function setF(k: keyof FormState, v: string) {
    setForm((prev) => ({ ...prev, [k]: v }))
  }

  function setLine(key: string, k: keyof LineForm, v: string) {
    setLines((prev) =>
      prev.map((l) => {
        if (l._key !== key) return l
        const updated = { ...l, [k]: v }
        if (k === 'po_line_id' && v) {
          const poline = poLines.find((pl) => pl.id === v)
          if (poline) {
            updated.description = poline.description
            updated.qty = String(poline.qty_ordered ?? 1)
            updated.unit_price = String(poline.unit_price ?? 0)
          }
        }
        return updated
      }),
    )
  }

  const subtotal = lines.reduce(
    (s, l) => s + parseFloat(l.qty || '0') * parseFloat(l.unit_price || '0'),
    0,
  )
  const tax = parseFloat(form.tax_amount || '0')
  const whtRate = form.wht_applies ? parseFloat(form.wht_rate || '0') / 100 : 0
  const wht = form.wht_applies ? subtotal * whtRate : 0
  const total = subtotal + tax
  const netPayable = total - wht

  async function handleSave() {
    if (!form.vendor_id) {
      addToast({ type: 'error', message: 'Vendor is required' })
      return
    }
    if (!form.invoice_number.trim()) {
      addToast({ type: 'error', message: 'Invoice number is required' })
      return
    }
    if (!form.invoice_date) {
      addToast({ type: 'error', message: 'Invoice date is required' })
      return
    }
    if (!form.due_date) {
      addToast({ type: 'error', message: 'Due date is required' })
      return
    }

    setSaving(true)
    const payload = {
      ...form,
      subtotal: subtotal,
      tax_amount: parseFloat(form.tax_amount || '0'),
      wht_applies: form.wht_applies,
      wht_rate: form.wht_applies ? parseFloat(form.wht_rate || '0') / 100 : 0,
      po_id: form.po_id || undefined,
      analytic_account_id: form.analytic_account_id || undefined,
      cost_center_id: form.cost_center_id || undefined,
      lines: lines
        .filter((l) => l.description.trim())
        .map((l) => ({
          po_line_id: l.po_line_id || undefined,
          description: l.description,
          qty: parseFloat(l.qty || '1'),
          unit_price: parseFloat(l.unit_price || '0'),
          account_id: l.account_id || undefined,
        })),
    }
    try {
      if (isEdit) {
        await api.put(`/finance/vendor-invoices/${id}`, payload)
        addToast({ type: 'success', message: 'Invoice updated' })
        navigate(`/finance/ap/${id}`)
      } else {
        const res = await api.post<{ id: string }>('/finance/vendor-invoices', payload)
        addToast({ type: 'success', message: 'Invoice created' })
        navigate(`/finance/ap/${res.data.id}`)
      }
    } catch (e: unknown) {
      if (apiErrCode(e) === 'DUPLICATE_INVOICE_NUMBER') {
        // Find the existing invoice by exact invoice_number match and navigate to it
        try {
          const res = await api.get<{ items: { id: string; invoice_number: string }[] }>(
            '/finance/vendor-invoices',
            {
              params: {
                vendor_id: form.vendor_id,
                invoice_number: form.invoice_number,
                cross_company: 'true',
                limit: 1,
              },
            },
          )
          const existing = res.data?.items?.[0]
          if (existing) {
            addToast({
              type: 'warning',
              message: `Invoice ${form.invoice_number} already exists for this vendor — opening it so you can link it to the PO`,
            })
            navigate(`/finance/ap/${existing.id}`)
            return
          }
        } catch {
          /* fall through */
        }
        addToast({
          type: 'error',
          message: `Invoice number "${form.invoice_number}" already exists for this vendor. Search for it in AP and link it to this PO manually.`,
        })
      } else {
        addToast({ type: 'error', message: apiErrMsg(e, 'Save failed') })
      }
    } finally {
      setSaving(false)
    }
  }

  if (loading)
    return (
      <div style={{ padding: '24px' }}>
        <div className="skeleton" style={{ height: 400 }} />
      </div>
    )

  const vendorPOs = pos.filter((p) => !form.vendor_id || p.vendor_id === form.vendor_id)

  const lineFields: LineItemField<LineForm>[] = [
    {
      key: 'po_line_id',
      label: 'PO line',
      width: '160px',
      render: (line) => (
        <SearchableSelect
          value={line.po_line_id}
          onChange={(v) => {
            setLine(line._key, 'po_line_id', v)
          }}
          placeholder="None"
          options={poLines.map((pl) => ({
            value: pl.id,
            label: pl.description?.slice(0, 30) ?? pl.id,
          }))}
        />
      ),
    },
    {
      key: 'description',
      label: 'Description',
      width: '220px',
      render: (line) => (
        <input
          value={line.description}
          onChange={(e) => {
            setLine(line._key, 'description', e.target.value)
          }}
          placeholder="Description…"
          style={inputStyle(theme as unknown as Record<string, string>)}
        />
      ),
    },
    {
      key: 'qty',
      label: 'Qty',
      width: '90px',
      render: (line) => (
        <input
          type="number"
          value={line.qty}
          onChange={(e) => {
            setLine(line._key, 'qty', e.target.value)
          }}
          style={inputStyle(theme as unknown as Record<string, string>)}
        />
      ),
    },
    {
      key: 'unit_price',
      label: 'Unit price',
      width: '120px',
      render: (line) => (
        <input
          type="number"
          value={line.unit_price}
          onChange={(e) => {
            setLine(line._key, 'unit_price', e.target.value)
          }}
          style={inputStyle(theme as unknown as Record<string, string>)}
        />
      ),
    },
    {
      key: 'total',
      label: 'Total',
      width: '110px',
      render: (line) => {
        const lineTotal = parseFloat(line.qty || '0') * parseFloat(line.unit_price || '0')
        return (
          <span style={{ color: theme.textPrimary, whiteSpace: 'nowrap' }}>
            {form.currency_code} {lineTotal.toLocaleString(undefined, { maximumFractionDigits: 2 })}
          </span>
        )
      },
    },
    {
      key: 'account_id',
      label: 'Account',
      width: '180px',
      render: (line) => (
        <SearchableSelect
          value={line.account_id}
          onChange={(v) => {
            setLine(line._key, 'account_id', v)
          }}
          placeholder="No account"
          options={chartAccounts.map((a) => ({
            value: a.id,
            label: `${a.code} ${a.name?.slice(0, 25) ?? ''}`,
          }))}
        />
      ),
    },
  ]

  return (
    <div style={{ padding: '24px', margin: '0 auto', maxWidth: '1200px' }}>
      <PageHeader
        title={isEdit ? 'Edit vendor invoice' : 'New vendor invoice'}
        actions={
          <div style={{ display: 'flex', gap: '8px' }}>
            <Button
              variant="ghost"
              size="sm"
              onClick={() => {
                navigate(isEdit ? `/finance/ap/${id}` : '/finance/ap')
              }}
            >
              Cancel
            </Button>
            <Button variant="primary" size="sm" onClick={handleSave} disabled={saving}>
              {saving ? 'Saving…' : 'Save invoice'}
            </Button>
          </div>
        }
      />

      <Card padding="md" style={{ marginBottom: '16px' }}>
        <h3
          style={{
            fontSize: '12px',
            fontWeight: 600,
            color: theme.textPrimary,
            marginBottom: '12px',
          }}
        >
          Invoice details
        </h3>
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
            gap: '12px',
          }}
        >
          <div>
            <SearchableSelect
              label="Vendor *"
              value={form.vendor_id}
              onChange={(v) => {
                setF('vendor_id', v)
              }}
              placeholder="Select vendor…"
              options={vendors.map((v) => ({ value: v.id, label: v.name }))}
              disabled={isEdit}
            />
          </div>
          <div>
            <SearchableSelect
              label="Purchase order (optional)"
              value={form.po_id}
              onChange={(v) => {
                setF('po_id', v)
              }}
              placeholder="None"
              options={vendorPOs.map((p) => ({ value: p.id, label: p.po_number }))}
              disabled={isEdit && !!form.po_id}
            />
          </div>
          <div>
            <label style={labelStyle(theme as unknown as Record<string, string>)}>
              Invoice number *
            </label>
            <input
              value={form.invoice_number}
              onChange={(e) => {
                setF('invoice_number', e.target.value)
              }}
              placeholder="INV-2024-001"
              style={inputStyle(theme as unknown as Record<string, string>)}
            />
          </div>
          <div>
            <Select
              label="Currency"
              value={form.currency_code}
              onChange={(e) => {
                setF('currency_code', e.target.value)
              }}
              options={CURRENCIES}
            />
          </div>
          <div>
            <label style={labelStyle(theme as unknown as Record<string, string>)}>
              Invoice date *
            </label>
            <input
              type="date"
              value={form.invoice_date}
              onChange={(e) => {
                setF('invoice_date', e.target.value)
              }}
              style={inputStyle(theme as unknown as Record<string, string>)}
            />
          </div>
          <div>
            <label style={labelStyle(theme as unknown as Record<string, string>)}>Due date *</label>
            <input
              type="date"
              value={form.due_date}
              onChange={(e) => {
                setF('due_date', e.target.value)
              }}
              style={inputStyle(theme as unknown as Record<string, string>)}
            />
          </div>
          <div>
            <SearchableSelect
              label="Cost center"
              value={form.cost_center_id}
              onChange={(v) => {
                setF('cost_center_id', v)
              }}
              placeholder="None"
              options={costCenters.map((c) => ({ value: c.id, label: `${c.code} — ${c.name}` }))}
            />
          </div>
          <div>
            <SearchableSelect
              label="Analytic account"
              value={form.analytic_account_id}
              onChange={(v) => {
                setF('analytic_account_id', v)
              }}
              placeholder="None"
              options={analyticAccounts.map((a) => ({
                value: a.id,
                label: `${a.code} — ${a.name}`,
              }))}
            />
          </div>
          <div style={{ gridColumn: '1 / -1' }}>
            <label style={labelStyle(theme as unknown as Record<string, string>)}>Notes</label>
            <textarea
              value={form.notes}
              onChange={(e) => {
                setF('notes', e.target.value)
              }}
              rows={2}
              style={{
                ...inputStyle(theme as unknown as Record<string, string>),
                resize: 'vertical',
              }}
            />
          </div>
        </div>
      </Card>

      {/* Lines */}
      <Card padding="none" style={{ marginBottom: '16px' }}>
        <div
          style={{
            padding: '12px 16px',
            borderBottom: `1px solid ${theme.border}`,
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
          }}
        >
          <h3 style={{ fontSize: '12px', fontWeight: 600, color: theme.textPrimary }}>
            Invoice lines
          </h3>
          <Button
            variant="secondary"
            size="sm"
            onClick={() => {
              setLines((prev) => [...prev, mkLine()])
            }}
          >
            + Add line
          </Button>
        </div>
        <div style={{ padding: '12px 16px' }}>
          <LineItemEditor
            fields={lineFields}
            rows={lines}
            rowKey={(row) => row._key}
            onRemoveRow={(idx) => {
              setLines((prev) => prev.filter((_, i) => i !== idx))
            }}
            removeDisabled={() => lines.length <= 1}
          />
        </div>
      </Card>

      {/* Totals */}
      <Card padding="md">
        <h3
          style={{
            fontSize: '12px',
            fontWeight: 600,
            color: theme.textPrimary,
            marginBottom: '12px',
          }}
        >
          Totals
        </h3>
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
            gap: '12px',
            marginBottom: '12px',
          }}
        >
          <div>
            <label style={labelStyle(theme as unknown as Record<string, string>)}>Tax amount</label>
            <input
              type="number"
              value={form.tax_amount}
              onChange={(e) => {
                setF('tax_amount', e.target.value)
              }}
              style={inputStyle(theme as unknown as Record<string, string>)}
            />
          </div>
          <div>
            <label style={labelStyle(theme as unknown as Record<string, string>)}>WHT</label>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginTop: '2px' }}>
              <input
                type="checkbox"
                checked={form.wht_applies}
                onChange={(e) => {
                  setForm((prev) => ({ ...prev, wht_applies: e.target.checked }))
                }}
                id="wht-applies"
              />
              <label
                htmlFor="wht-applies"
                style={{ fontSize: '12px', color: theme.textPrimary, cursor: 'pointer' }}
              >
                Deduct WHT
              </label>
              {form.wht_applies && (
                <>
                  <input
                    type="number"
                    value={form.wht_rate}
                    onChange={(e) => {
                      setForm((prev) => ({ ...prev, wht_rate: e.target.value }))
                    }}
                    placeholder="Rate %"
                    min="0"
                    max="100"
                    step="0.1"
                    style={{
                      ...inputStyle(theme as unknown as Record<string, string>),
                      width: '80px',
                    }}
                  />
                  <span style={{ fontSize: '12px', color: theme.textMuted }}>%</span>
                </>
              )}
            </div>
          </div>
        </div>
        <div style={{ borderTop: `1px solid ${theme.border}`, paddingTop: '10px' }}>
          {[
            { label: 'Subtotal', value: subtotal },
            { label: 'Tax', value: tax },
            { label: 'WHT', value: -wht },
            { label: 'Total', value: total, bold: true },
            { label: 'Net payable', value: netPayable, bold: true, color: theme.accent },
          ].map((row) => (
            <div
              key={row.label}
              style={{
                display: 'flex',
                justifyContent: 'space-between',
                padding: '3px 0',
                fontSize: '12px',
              }}
            >
              <span style={{ color: theme.textMuted }}>{row.label}</span>
              <span
                style={{ color: row.color ?? theme.textPrimary, fontWeight: row.bold ? 700 : 400 }}
              >
                {form.currency_code}{' '}
                {row.value.toLocaleString(undefined, { maximumFractionDigits: 2 })}
              </span>
            </div>
          ))}
        </div>
      </Card>
    </div>
  )
}
