-- Migration 045: Canonical permission registry update
-- Removes old/renamed permission keys introduced in the Prompt 1 draft registry.
-- New canonical keys are upserted by running: pnpm seed:permissions

-- ── Step 1: Remove orphaned user_permissions rows ────────────────────────────
DELETE FROM user_permissions
WHERE permission_key IN (
  -- Finance: old granular action keys replaced by view/edit/approve/admin
  'finance.journals.create',
  'finance.journals.delete',
  'finance.journals.export',
  'finance.chart_of_accounts.view',
  'finance.chart_of_accounts.manage',
  'finance.fx.view',
  'finance.fx.manage',
  'finance.reports.export',

  -- Projects: old nested projects.projects.* replaced by flat projects.*
  'projects.projects.view',
  'projects.projects.create',
  'projects.projects.edit',
  'projects.projects.delete',
  'projects.projects.manage_team',
  'projects.invoices.create',
  'projects.invoices.issue',
  'projects.invoices.approve',
  'projects.invoices.void',
  'projects.invoices.export',
  'projects.lifecycles.view',
  'projects.lifecycles.manage',
  'projects.timesheets.view',
  'projects.timesheets.submit',
  'projects.timesheets.approve',

  -- Manufacturing: old granular keys + old bom/inventory submodules
  'manufacturing.orders.create',
  'manufacturing.orders.complete',
  'manufacturing.bom.view',
  'manufacturing.bom.manage',
  'manufacturing.inventory.view',
  'manufacturing.inventory.adjust',
  'manufacturing.inventory.transfer',

  -- Rental: old equipment.* replaced by rental.assets.*, old contract actions
  'rental.equipment.view',
  'rental.equipment.manage',
  'rental.equipment.retire',
  'rental.contracts.create',
  'rental.contracts.approve',
  'rental.contracts.terminate',

  -- HR: granular employee actions + old payroll submodule (moved to payroll.*)
  'hr.employees.create',
  'hr.employees.delete',
  'hr.employees.view_salary',
  'hr.employees.manage_salary',
  'hr.leave.submit',
  'hr.payroll.view',
  'hr.payroll.process',
  'hr.payroll.approve',

  -- Procurement: old purchase_orders.* replaced by procurement.po.*
  'procurement.purchase_orders.view',
  'procurement.purchase_orders.create',
  'procurement.purchase_orders.edit',
  'procurement.purchase_orders.approve',
  'procurement.purchase_orders.receive',
  'procurement.suppliers.view',
  'procurement.suppliers.manage',

  -- Reporting: old dashboards + old reports submodule
  'reporting.dashboards.view',
  'reporting.dashboards.manage',
  'reporting.reports.view',
  'reporting.reports.export',
  'reporting.reports.schedule',

  -- Interco: old interco.stock.* replaced by interco.transactions.* + interco.stock_transfers.*
  'interco.stock.view',
  'interco.stock.transfer',
  'interco.stock.approve',

  -- Admin: collapsed to view/edit; audit submodule removed; companies.edit → companies.admin
  'admin.users.create',
  'admin.users.deactivate',
  'admin.users.manage_permissions',
  'admin.companies.edit',
  'admin.audit.view',
  'admin.audit.export'
);

-- ── Step 2: Remove orphaned role_template_permissions rows ───────────────────
DELETE FROM role_template_permissions
WHERE permission_key IN (
  'finance.journals.create',
  'finance.journals.delete',
  'finance.journals.export',
  'finance.chart_of_accounts.view',
  'finance.chart_of_accounts.manage',
  'finance.fx.view',
  'finance.fx.manage',
  'finance.reports.export',
  'projects.projects.view',
  'projects.projects.create',
  'projects.projects.edit',
  'projects.projects.delete',
  'projects.projects.manage_team',
  'projects.invoices.create',
  'projects.invoices.issue',
  'projects.invoices.approve',
  'projects.invoices.void',
  'projects.invoices.export',
  'projects.lifecycles.view',
  'projects.lifecycles.manage',
  'projects.timesheets.view',
  'projects.timesheets.submit',
  'projects.timesheets.approve',
  'manufacturing.orders.create',
  'manufacturing.orders.complete',
  'manufacturing.bom.view',
  'manufacturing.bom.manage',
  'manufacturing.inventory.view',
  'manufacturing.inventory.adjust',
  'manufacturing.inventory.transfer',
  'rental.equipment.view',
  'rental.equipment.manage',
  'rental.equipment.retire',
  'rental.contracts.create',
  'rental.contracts.approve',
  'rental.contracts.terminate',
  'hr.employees.create',
  'hr.employees.delete',
  'hr.employees.view_salary',
  'hr.employees.manage_salary',
  'hr.leave.submit',
  'hr.payroll.view',
  'hr.payroll.process',
  'hr.payroll.approve',
  'procurement.purchase_orders.view',
  'procurement.purchase_orders.create',
  'procurement.purchase_orders.edit',
  'procurement.purchase_orders.approve',
  'procurement.purchase_orders.receive',
  'procurement.suppliers.view',
  'procurement.suppliers.manage',
  'reporting.dashboards.view',
  'reporting.dashboards.manage',
  'reporting.reports.view',
  'reporting.reports.export',
  'reporting.reports.schedule',
  'interco.stock.view',
  'interco.stock.transfer',
  'interco.stock.approve',
  'admin.users.create',
  'admin.users.deactivate',
  'admin.users.manage_permissions',
  'admin.companies.edit',
  'admin.audit.view',
  'admin.audit.export'
);

-- ── Step 3: Delete old permission rows ───────────────────────────────────────
DELETE FROM permissions
WHERE key IN (
  'finance.journals.create',
  'finance.journals.delete',
  'finance.journals.export',
  'finance.chart_of_accounts.view',
  'finance.chart_of_accounts.manage',
  'finance.fx.view',
  'finance.fx.manage',
  'finance.reports.export',
  'projects.projects.view',
  'projects.projects.create',
  'projects.projects.edit',
  'projects.projects.delete',
  'projects.projects.manage_team',
  'projects.invoices.create',
  'projects.invoices.issue',
  'projects.invoices.approve',
  'projects.invoices.void',
  'projects.invoices.export',
  'projects.lifecycles.view',
  'projects.lifecycles.manage',
  'projects.timesheets.view',
  'projects.timesheets.submit',
  'projects.timesheets.approve',
  'manufacturing.orders.create',
  'manufacturing.orders.complete',
  'manufacturing.bom.view',
  'manufacturing.bom.manage',
  'manufacturing.inventory.view',
  'manufacturing.inventory.adjust',
  'manufacturing.inventory.transfer',
  'rental.equipment.view',
  'rental.equipment.manage',
  'rental.equipment.retire',
  'rental.contracts.create',
  'rental.contracts.approve',
  'rental.contracts.terminate',
  'hr.employees.create',
  'hr.employees.delete',
  'hr.employees.view_salary',
  'hr.employees.manage_salary',
  'hr.leave.submit',
  'hr.payroll.view',
  'hr.payroll.process',
  'hr.payroll.approve',
  'procurement.purchase_orders.view',
  'procurement.purchase_orders.create',
  'procurement.purchase_orders.edit',
  'procurement.purchase_orders.approve',
  'procurement.purchase_orders.receive',
  'procurement.suppliers.view',
  'procurement.suppliers.manage',
  'reporting.dashboards.view',
  'reporting.dashboards.manage',
  'reporting.reports.view',
  'reporting.reports.export',
  'reporting.reports.schedule',
  'interco.stock.view',
  'interco.stock.transfer',
  'interco.stock.approve',
  'admin.users.create',
  'admin.users.deactivate',
  'admin.users.manage_permissions',
  'admin.companies.edit',
  'admin.audit.view',
  'admin.audit.export'
);

-- After running this migration, execute: pnpm seed:permissions
-- That will upsert all 95 canonical keys into the permissions table.
